import "@styles/global.css";
import { BaseProvider } from "./(utils)/context/BaseContext";
// import Auth from "@components/Auth";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <BaseProvider>{children}</BaseProvider>
      </body>
    </html>
  );
}
